### PR TITLE
chore(core_crypto): fix overflows in tests

### LINKED ISSUE #136: run tfhe-rs in macos m1 aarch64
**Describe the bug**
run tfhe-rs in macos aarch64 

**Evidence**
error: failed to select a version for `tfhe`.
    ... required by package `tfhetest v0.1.0 (/Users/miao/Documents/Miao/2021 MA/rust_projects/tfhetest)`
versions that meet the requirements `*` are: 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.0.0

the package `tfhetest` depends on `tfhe`, with features: `aarch64-unix` but `tfhe` does not have these features.

failed to select a version for `tfhe` which could resolve this conflict
image

**Configuration(please complete the following information):**
 - OS: macos m1

### PR DESCRIPTION
**Pull request by tmontaigu**
These overflows appeared in debug builds,
and are easly fixed by using explicit wrapping operation or correct values.

Fixes #136 (even tho running test in debug mode is not recommended)

### CODE REVIEW

File: tfhe/src/core_crypto/algorithms/lwe_encryption.rs [hunk 1]
```diff
@@ -1368,7 +1368,7 @@ mod test {
             );
             // Create the plaintext
             let msg: Scalar = test_tools::random_uint_between(Scalar::ZERO..Scalar::TWO.shl(2));
-            let encoded_msg = msg << 60;
+            let encoded_msg = msg << 28;
```
Comment (IceTDrinker) [inline tfhe/src/core_crypto/algorithms/lwe_encryption.rs:1371]:
```
msg << (Scalar::BITS - 4)
```
that's better for the spirit of the encoding we were kind of doing here

**Review by IceTDrinker — APPROVED** [review]

File: tfhe/src/core_crypto/algorithms/lwe_encryption.rs (hunk 1 above)
Comment (tmontaigu) [reply tfhe/src/core_crypto/algorithms/lwe_encryption.rs:1371]: Shouldn't it be `msg << (Scalar::BITS - 5)` for the padding bit ?

Comment (IceTDrinker) [reply tfhe/src/core_crypto/algorithms/lwe_encryption.rs:1371]: strictly yes

**Review by IceTDrinker — APPROVED** [review]
Thanks !

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
can you try rebasing on main ? I modified something linked to slow download times in the docker, it might help
